---
- name: Install & configure Waveshare 2.8" DPI LCD with touch (Bookworm)
  hosts: local
  gather_facts: true
  become: true

  roles:
    - role: install_rpi_update_client
    - role: apt
    - role: network_wifi_static
    - role: install_28_dpi_lcd_touch_screen
    - role: mate
    - role: mate_autologin
