#!/usr/bin/env bash
set -euo pipefail

# sprawdzenie czy skrypt działa jako root
if [[ "${EUID}" -ne 0 ]]; then
    echo "❌ Ten skrypt musi być uruchomiony jako root (np. przez: sudo $0)" >&2
    exit 1
fi

REAL_USER="${SUDO_USER:-$USER}"

echo "✔ Skrypt uruchomiony z uprawnieniami root."

REQUIRED_PACKAGES=("python3-venv" "python3-pip" "git")

echo -n "Sprawdzanie wymaganych pakietów"
install_packages=""

for package_name in "${REQUIRED_PACKAGES[@]}"; do
    if dpkg -s "${package_name}" &> /dev/null; then
        echo -n "."
    else
        install_packages="${package_name}"
    fi
done
echo

if [ -n "${install_packages}" ]; then
    sudo apt-get update -y
    sudo apt-get install -y ${install_packages}
fi

venv_path="/home/${REAL_USER}/.venv"

if [[ ! -d "${venv_path}" ]]; then
    echo "Tworzenie wirtualnego środowiska w ${venv_path} ..."
    cd /home/${USER}
    python3 -m venv .venv
    source ${venv_path}/bin/activate
    pip install ansible

    if ! grep -Fxq "alias rpi-update-client='sudo /home/${USER}/ansible_rpi/rpi-update-client'" ~/.bashrc; then
        echo "alias rpi-update-client='sudo /home/${USER}/ansible_rpi/rpi-update-client'" >> ~/.bashrc
    fi
    echo "✔ Wirtualne środowisko zostało utworzone."
fi

echo "✔ Wczytuję wirtualne środowisko z ${venv_path}"
source /home/${USER}/.venv/bin/activate
cd /home/${USER}/ansible_rpi || exit 2
echo "✔ Aktualizuję repozytorium i uruchamiam aktualizację..."
git pull && ansible-playbook -i inventory.ini playbook.yml && echo "✔ Aktualizacja zakończona."

