---
- name: Ensure KMS overlays block present (Bookworm)
  blockinfile:
    path: "{{ config_txt }}"
    marker: "# {mark} ANSIBLE Waveshare 2.8 DPI (Bookworm/KMS)"
    block: "{{ kms_block }}"

- name: Find role-local dtbo files (if any)
  find:
    paths: "{{ dtbo_dir }}"
    patterns: "*.dtbo"
    file_type: file
  register: dtbo_files
  failed_when: false

- name: Copy dtbo files into overlays dir (skip if exists)
  copy:
    src: "{{ item.path }}"
    dest: "{{ overlays_dir }}/{{ item.path | basename }}"
    mode: "0644"
    force: no
  loop: "{{ (dtbo_files.files | default([])) }}"
  loop_control:
    label: "{{ item.path | basename }}"

- name: Rotate screen
  ansible.builtin.replace:
    path: "{{ ansible_env.HOME }}/.config/kanshi/config"
    # Searches for: line starting with "output", anywhere after "transform <0|90|180|270>"
    regexp: '(^\s*output\b[^\n]*?\btransform\s+)(?:0|90|180|270)\b'
    replace: '\g<1>90'
    backup: true