---
# KMS dla Bookworm: vc4-kms-v3d + tylko te overlaye, które realnie istnieją.

- name: Build KMS block for config.txt from overlays_to_enable
  set_fact:
    kms_block: |-
      dtoverlay=vc4-kms-v3d
      {% for ov in overlays_to_enable %}
      dtoverlay={{ ov }}
      {% endfor %}

- name: Ensure KMS overlays block present (Bookworm)
  blockinfile:
    path: "{{ config_txt }}"
    marker: "# {mark} ANSIBLE Waveshare 2.8 DPI (Bookworm/KMS)"
    block: "{{ kms_block }}"

- name: Comment out legacy FKMS line if present (safety)
  replace:
    path: "{{ config_txt }}"
    regexp: '^dtoverlay=vc4-fkms-v3d'
    replace: '# dtoverlay=vc4-fkms-v3d (disabled by Ansible)'
