---
- name: Configure legacy DPI block in config.txt (fallback on Bookworm)
  blockinfile:
    path: "{{ config_txt }}"
    marker: "# {mark} ANSIBLE Waveshare 2.8 DPI (Bookworm legacy fallback)"
    block: |
      gpio=0-9=a2
      gpio=12-17=a2
      gpio=20-25=a2
      dtoverlay=dpi24
      enable_dpi_lcd=1
      display_default_lcd=1
      extra_transpose_buffer=2
      dpi_group=2
      dpi_mode=87
      dpi_output_format=0x7F216
      hdmi_timings=480 0 26 16 10 640 0 25 10 15 0 0 0 60 0 32000000 1

- name: Ensure KMS is commented out (safety on legacy)
  replace:
    path: "{{ config_txt }}"
    regexp: '^(dtoverlay=vc4-kms-v3d|dtoverlay=vc4-fkms-v3d)'
    replace: '# \1 (disabled by Ansible - legacy DPI fallback)'

- name: Note about touch overlays (legacy)
  debug:
    msg: >-
      Legacy fallback nie dodaje overlayów dotyku Waveshare (jeśli ich nie ma).
      Jeżeli dotyk nie działa, rozważ update firmware/overlays lub własny overlay touch.
