---
# 1) Zbierz overlaye już dostępne w systemie
- name: List existing system DTBOs in overlays dir
  find:
    paths: "{{ overlays_dir }}"
    patterns: "*.dtbo"
    file_type: file
  register: sys_dtbo

# 2) Pobierz paczkę (best-effort)
- name: Create temp dir for dtbo zip
  tempfile:
    state: directory
    suffix: dtbo
  register: tmp_dtbo

- name: Download DTBO zip from Waveshare (best-effort)
  get_url:
    url: "{{ install_28_dpi_lcd_touch_screen_dtbo_zip_url }}"
    dest: "{{ tmp_dtbo.path }}/{{ install_28_dpi_lcd_touch_screen_dtbo_zip_name }}"
    mode: "0644"
  register: dtbo_download
  failed_when: false
  retries: 2
  delay: 3
  until: dtbo_download is succeeded or dtbo_download is failed

- name: Unarchive DTBO zip (if downloaded)
  unarchive:
    src: "{{ tmp_dtbo.path }}/{{ install_28_dpi_lcd_touch_screen_dtbo_zip_name }}"
    dest: "{{ tmp_dtbo.path }}"
    remote_src: true
  when: dtbo_download is succeeded
  register: unz
  failed_when: false

- name: Find extracted dtbo files (if any)
  find:
    paths: "{{ tmp_dtbo.path }}"
    patterns: "*.dtbo"
    file_type: file
  register: found_dtbo
  when: dtbo_download is succeeded
  failed_when: false

# 3) Skopiuj tylko te dtbo, które mamy w paczce (nie nadpisuj istniejących)
- name: Copy extracted dtbo files into overlays dir (skip if exists)
  copy:
    src: "{{ item.path }}"
    dest: "{{ overlays_dir }}/{{ item.path | basename }}"
    mode: "0644"
    force: no
  loop: "{{ (found_dtbo.files | default([])) }}"
  loop_control:
    label: "{{ item.path | basename }}"

# 4) Ustal listę overlayów, które realnie są dostępne
- name: Compute available dtbo basenames (system + extracted)
  set_fact:
    available_dtbo_basenames: >-
      {{ ( (sys_dtbo.files | map(attribute='path') | map('basename') | list)
         + (found_dtbo.files | default([]) | map(attribute='path') | map('basename') | list) )
         | unique }}

# 5) Zminimalizuj wymagania: dla Bookworm/KMS MUSI istnieć vc4-kms-dpi-2inch8.dtbo
- name: Ensure minimal required DTBO exists (vc4-kms-dpi-2inch8.dtbo)
  assert:
    that:
      - "'vc4-kms-dpi-2inch8.dtbo' in available_dtbo_basenames"
    fail_msg: >-
      Brak 'vc4-kms-dpi-2inch8.dtbo' w {{ overlays_dir }} i nie udało się pobrać z Waveshare.
      Zaktualizuj firmware/bootloader (sudo apt update && sudo apt full-upgrade; ewentualnie raspberrypi-bootloader),
      lub podaj alternatywny URL w 'install_28_dpi_lcd_touch_screen_dtbo_zip_url'.

# 6) Zbuduj listę overlayów do użycia (tylko te, które istnieją)
- name: Build overlays_to_enable list (present ones only)
  set_fact:
    overlays_to_enable: >-
      {{
        [
          'waveshare-28dpi-3b-4b.dtbo',
          'waveshare-28dpi-3b.dtbo',
          'waveshare-28dpi-4b.dtbo',
          'waveshare-touch-28dpi.dtbo',
          'vc4-kms-dpi-2inch8.dtbo'
        ]
        | select('in', available_dtbo_basenames)
        | map('regex_replace', '\\.dtbo$', '')
        | list
      }}

- name: Debug overlays to enable (for visibility)
  debug:
    var: overlays_to_enable
