---
- name: Ensure base packages are installed (Bookworm)
  apt:
    name:
      - unzip
      - i2c-tools
      - libraspberrypi-bin
      - libdrm-tests
    state: present
    update_cache: no  # cache aktualizuje rola "apt"

- name: Ensure i2c_arm is enabled in config.txt
  lineinfile:
    path: "{{ config_txt }}"
    line: "dtparam=i2c_arm=on"
    state: present
    create: yes
    insertafter: EOF
