---
#waveshare_28_lcd_dpi_touch_screen_dtbo_files:
#  - waveshare-28dpi-3b-4b.dtbo
#  - waveshare-28dpi-3b.dtbo
#  - waveshare-28dpi-4b.dtbo
#  - waveshare-touch-28dpi.dtbo
#  - vc4-kms-dpi-2inch8.dtbo

dtbo_dir: "{{ role_path }}/files/28DPI-DTBO"


kms_block: |-
  dtoverlay=vc4-kms-v3d
  dtoverlay=waveshare-28dpi-3b-4b
  dtoverlay=waveshare-28dpi-3b
  dtoverlay=waveshare-28dpi-4b
  dtoverlay=waveshare-touch-28dpi
  dtoverlay=vc4-kms-dpi-2inch8
